In [1]:
# Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import os
import re
import datetime

In [3]:
url = r"C:\Users\user\Analytics_Assignment.xlsx"
df = pd.read_excel(url, sheet_name = 0)
pd.set_option('display.max_columns', 500)
df

,PAN Key,BIRTH_DATE,FH_KYC,KYC_STATUS_DESC,OCCUPATION_CODE,OCCUPADESC,PINCODE,SMS_ALERT,GENDER,MARITAL_STATUS,CONTACTABILITY,NOMINATION_TAG,NOMINATION_RELATION,SEGMENT,INVTYPDESC,REGION,STATE,BRANCH,MIS_COUNTRY,TOP_T30_B30,CAMS_LOCATION,AGE,RETAIL_FLAG,RETAIL_FLAG_CAMS,INSTITUTIONAL_FLAG,FIRST_APPL_NO,First broker Key,VINTAGE_DATE,FIRST_TRXN_SUBTYPE_CODE,LAST_APPL_NO,Last Broker Key1,LAST_RECENCY_DATE,LAST_SCH_CODE,Last Scheme Name,LAST_TRXN_SUBTYPE_CODE,SOURCE1,LUMPSUM_PURCHASE,SIP_PURCHASE,TOTAL_PURCHASE,LUMPSUM_PROP,NO_OF_LUMPSUM_PURCHASES,NO_OF_SIP_PURCHASES,NO_OF_PURCHASES,VINTAGE,RECENCY,LATENCY,ONLINE_OFFLINE_TAG,FIRST_BROKER_CAT,LAST_BROKER_CAT,FIRST_PRODUCT,FIRST_MODE,Scheme Code,Scheme Name,REDEMPTION_TRXN_COUNT,GROSS_SALES,ATS_LUMPSUM,ATS_SIP,NO_OF_POS_TRXN,NO_OF_TRXN,EQUITY_GS,DEBT_GS,LIQUID_GS,AUM,EQUITY_AUM,DEBT_AUM,LIQUID_AUM,NO_OF_SCHEMES,NO_OF_ASSET_CLASS,STATUS,NO_OF_CHANNEL,PPD_STATUS,ACQUISITION_DATE,LATENCY_CLEAN,REGISTERED_ONLINE,ARBITRAGE_FUND_GS,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_GS,BANKING_AND_PSU_FUND_GS,CAPITAL_PROTECTION_ORIENTED_SCHEMES_GS,CONSERVATIVE_HYBRID_FUND_GS,CORPORATE_BOND_FUND_GS,CREDIT_RISK_FUND_GS,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_GS,DYNAMIC_BOND_FUND_GS,ELSS_GS,EQUITY_OTHERS_C_GS,EQUITY_SAVINGS_FUND_GS,FIXED_TERM_PLAN_GS,FLEXI_CAP_FUND_GS,FLOATER_FUND_GS,FOCUSED_FUND_GS,FUND_OF_FUND_DOMESTIC_GS,FUND_OF_FUND_OVERSEAS_GS,GILT_FUND_GS,GOLD_ETFS_GS,INDEX_FUNDS_DEBT_GS,INDEX_FUNDS_EQUITY_GS,LARGE_MID_CAP_FUND_GS,LARGE_CAP_FUND_GS,LIQUID_FUND_GS,LOW_DURATION_FUND_GS,MEDIUM_DURATION_FUND_GS,MEDIUM_TO_LONG_DURATION_FUND_GS,MID_CAP_FUND_GS,MONEY_MARKET_FUND_GS,MULTI_CAP_FUND_GS,OTHER_ETFS_GS,OVERNIGHT_FUND_GS,SECTORAL_THEMATIC_FUNDS_GS,SHORT_DURATION_FUND_GS,SMALL_CAP_FUND_GS,ULTRA_SHORT_DURATION_FUND_GS,VALUE_FUND_CONTRA_FUND_GS,ARBITRAGE_FUND_AUM,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_AUM,BANKING_AND_PSU_FUND_AUM,CAPITAL_PROTECTION_ORIENTED_SCHEMES_AUM,CONSERVATIVE_HYBRID_FUND_AUM,CORPORATE_BOND_FUND_AUM,CREDIT_RISK_FUND_AUM,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_AUM,DYNAMIC_BOND_FUND_AUM,ELSS_AUM,EQUITY_OTHERS_C_AUM,EQUITY_SAVINGS_FUND_AUM,FIXED_TERM_PLAN_AUM,FLEXI_CAP_FUND_AUM,FLOATER_FUND_AUM,FOCUSED_FUND_AUM,FUND_OF_FUND_DOMESTIC_AUM,FUND_OF_FUND_OVERSEAS_AUM,GILT_FUND_AUM,GOLD_ETFS_AUM,INDEX_FUNDS_DEBT_AUM,INDEX_FUNDS_EQUITY_AUM,LARGE_MID_CAP_FUND_AUM,LARGE_CAP_FUND_AUM,LIQUID_FUND_AUM,LOW_DURATION_FUND_AUM,MEDIUM_DURATION_FUND_AUM,MEDIUM_TO_LONG_DURATION_FUND_AUM,MID_CAP_FUND_AUM,MONEY_MARKET_FUND_AUM,MULTI_CAP_FUND_AUM,OTHER_ETFS_AUM,OVERNIGHT_FUND_AUM,SECTORAL_THEMATIC_FUNDS_AUM,SHORT_DURATION_FUND_AUM,SMALL_CAP_FUND_AUM,ULTRA_SHORT_DURATION_FUND_AUM,VALUE_FUND_CONTRA_FUND_AUM,RISK_VALUE,RISK_APPETITE,LIVE_SIP,ATS_SIP_LIVE,AHT,COST_VALUE,NEGATIVE_AMT,ABS_RETURNS,POSITIVE_AMT_DEBT,NEGATIVE_AMT_DEBT,ABS_RETURNS_DEBT,POSITIVE_AMT_EQUITY,NEGATIVE_AMT_EQUITY,ABS_RETURNS_EQUITY,POSITIVE_AMT_LIQUID,NEGATIVE_AMT_LIQUID,ABS_RETURNS_LIQUID,XIRR_EQUITY,XIRR_DEBT,XIRR_LIQUID,XIRR,Profiling status,Income,Urban,Lifestyle,SEC Reference,Lifestyle > Smaller Towns,Special Health Care Target Group,Saving Plan,Retirement Plan,Unit Linked Plan,Health,Mutual Fund,Fixed Deposit,Credit Card Holding,"01: Entry Price - Segment INR 2,00,000 – 4,50,000","02: Entry Premium Hatch Segment INR 4,00,000 – 7,00,000","03: Premium Hatch Segment INR 5,50,000 – 9,00,000","04: Compact Sedan Segment INR 5,30,000 – 8,50,000","05: Sedan Segment INR 8,00,000 – 13,00,000","06: Premium Sedan Segment INR 13,00,000 – 20,00,000","07: Compact / Entry SUV Segment INR 9,00,000 – 14,00,000","08: SUV Segment INR 15,00,000 – 30,00,000","09: Luxury Premium Sedan & SUV Segment INR 25,00,000+",10: Second-hand Sedan Segment car,11: Second-hand Premium Sedan / SUV Segment,12: Second-hand Luxury Premium Sedan & SUV Segment,Purchase Price Segment,Laundry > Fabric Wash Products,Laundry > Washing Machine Products,Personal Wash,Packaged Food,Cosmetics,Purchase Price Category,Purchase Category > Total,Purchase Category > Gold,Purchase Category > Diamond,Spend Category,Destination Category,Special Category,Online Shopping Channels,Product Category Home and Living,01: Entry Level Scooter Segment,02: Premium Scooter Segment,03: Entry Level Commuter Segment,04: Premium Commuter Segment,05: Entry Level Sports Bike Segment,06: Premium Sports Bike Segment,07: Entry Level Cruiser Bike Segment,08: Premium Cruiser Bike Segment,09: Touring Bike Segment,10: Off Road Bike Segment
0,1,NaT,3.0,KYC Completed,NaN,NaN,400051,N,NaN,NaN,Email available,N,NaN,Domestic Corp,Body Corporate,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,NaN,Institutional,Institutional,Insti,NaN,1.0,2017-10-24,N,NaN,1.0,2021-01-14,205G,NaN,N,ITN-eScan,5000000.00,0.00,5000000.00,1.00,1.0,NaN,1,5.08,1.85,NaN,Offline,CORPORATE DISTRIBUTOR,CORPORATE DISTRIBUTOR,Debt,Lumpsum,48,Kotak Medium Term Fund,NaN,11165243.0,5000000.0,NaN,1.0,3,NaN,11165243.06,NaN,6584041.19,NaN,6584041.19,NaN,2.0,1.0,Active,1.0,N,2017-10-24,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6165243.0,5000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6584041.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,Moderate,NaN,NaN,3.21546,6165242.0,6165551.32,14.19001,11165243.06,6165551.32,14.19001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.036014,NaN,NaN,Profiled-Urban,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,03: Aspiring Urban Middle Class,04: SEC B1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,0,Yes,0,0,02: Expected Moderate / Average Use,0,0,Yes,Yes,0,0,0,0,0,0,0,0,"03: INR 51,00,000 - 1 Crore",01: Mass Fabric Products,Yes,02: Popular Classified Products,02: Premium Classified Products,02: Popular Classified Products,"02: “Medium"" INR 800 – 1,500",01: Branded Jewellery,03: Moderately priced Gold Jewellery,05: Moderately priced Diamond Jewellery,01: Basic,01: National,0,Yes,02: Moderate Priced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaT,3.0,KYC Completed,1,Business,400058,Y,NaN,NaN,Email available,N,NaN,Domestic Corp,Public Limited Company,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,NaN,Retail,Institutional,Insti,NaN,2.0,2018-01-04,N,NaN,217.0,2022-08-22,108,NaN,S,eISC,6299860.00,1599920.00,7899780.00,0.79,3.0,1.0,4,4.88,0.25,1.63,Offline,MUTUAL FUND DISTRIBUTOR,NATIONAL DISTRIBUTOR,NaN,Lumpsum,463,NaN,NaN,18195798.0,2099953.0,399980.0,9.0,915,8192419.07,NaN,4503478.63,11783596.42,11783596.42,NaN,NaN,3.0,2.0,Active,2.0,N,2018-01-04,1.63,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5792539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2399880.0,NaN,4503479.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9314442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2469155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,1.0,400000.0,3.36743,8192419.0,10296017.70,19.42334,NaN,NaN,NaN,8192419.07,0.00,43.83537,4692627.84,4692539.07,-0.00189,0.122454,NaN,0.00000,NaN,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,02: SEC A2,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,02: Popular Classified Products,"03: ""Premium"" INR 1,500 – 3,500",01: Branded Jewellery,04: High priced Gold Jewellery,0,01: Basic,01: National,0,Yes,02: Moderate Priced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaT,3.0,KYC Completed,8,Others,400072,Y,NaN,NaN,Both available,N,NaN,Domestic Corp,Body Corporate,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,NaN,Retail,Institutional,Insti,1909170764,3.0,2017-09-18,N,190922003587,3.0,2022-09-28,274,NaN,N,Distributor,9859525.01,0.00,9859525.01,1.00,11.0,NaN,11,5.18,0.15,0.52,Online,BANKS,BANKS,NaN,Lumpsum,253,NaN,302.0,11577903.0,896320.0,NaN,11.0,385,10514245.16,503668.30,199990.00,10066215.93,9687882.54,343482.83,34850.57,11.0,3.0,Active,2.0,N,2017-09-18,0.52,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4499775.0,NaN,NaN,500000.0,NaN,NaN,860000.0,NaN,999900.0,NaN,499975.0,NaN,NaN,NaN,NaN,NaN,166652.0,199990.0,NaN,NaN,NaN,NaN,3693.0,299985.0,NaN,NaN,3187933.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4898453.0,NaN,NaN,NaN,NaN,NaN,848034.0,NaN,NaN,NaN,343483.0,NaN,NaN,NaN,NaN,NaN,169139.0,34851.0,NaN,NaN,NaN,NaN,NaN,318974.0,NaN,NaN,3453283.0,NaN,NaN,NaN,NaN,1.858751,Low to Moderate,NaN,NaN,1.19710,9188754.0,2940795.74,12.30644,503785.23,3859.73,-31.05345,10514245.16,2406582.71,15.02933,199990.00,166660.00,0.76032,0.067900,-0.247453,NaN,NaN,Profiled-Urban,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,05: Successful Urban Fast Climbers,06: SEC C1,0,02: Health Care - ‘The Carefree / Anxious’ In ...,01: Saving Plan,Yes,0,Yes,0,0,0,0,0,Yes,Yes,0,0,0,0,0,0,0,0,"03: INR 51,00,000 - 1 Crore",01: Mass Fabric Products,Yes,02: Popular Classified Products,01: Mass Classified Products,02: Popular Classified Products,"02: “Medium"" INR 800 – 1,500",02: Traditional / Non-branded Jewellery,03: Moderately priced Gold Jewellery,05: Moderately priced Diamond Jewellery,01: Basic,01: National,0,0,02: Moderate Priced,01: Entry Level Scooter Segment,NaN,03: Entry Level Commuter Segment,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1956-07-11,3.0,KYC Completed,3,Professional,400006,Y,M,1.0,Both available,N,NaN,HNI,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,66.0,Retail,Retail,Retail,CA8700476,4.0,2015-07-17,N,NaN,4.0,2022-10-25,13,NaN,N,ITN-eScan,52348080.10,0.00,52348080.10,1.00,13.0,NaN,13,7.34,0.07,0.61,Offline,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,37,Kotak Equity Saving Fund,6.0,67868914.0,4026775.0,NaN,13.0,57,27670739.32,3700000.00,36498175.10,27936316.97,26839053.64,NaN,1097263.33,10.0,3.0,Active,1.0,N,2015-07-17,0.61,N,NaN,NaN,NaN,NaN,NaN,NaN,3700000.0,1499925.0,NaN,NaN,NaN,8738804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3399830.0,7532306.0,36498175.0,NaN,NaN,NaN,4000000.0,NaN,NaN,NaN,NaN,2499875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1532678.0,NaN,NaN,NaN,5317325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3634823.0,5698805.0,1097263.0,NaN,NaN,NaN,7652323.0,NaN,NaN,NaN,NaN,3003100.0,NaN,NaN,NaN,NaN,4.942699,High,NaN,NaN,3.05478,22496618.0,48213020.49,12.20061,3700000.00,4691410.15,26.79487,27670739.32,7521610.34,24.17689,36498175.10,36000000.00,1.64142,0.126981,0.000000,-0.02874,NaN,Profiled-Urban,"08: Very High INR > 3,00,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,01: SEC A1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,0,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,0,0,0,Yes,0,0,Yes,05: Beyond INR 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"05: ""Luxury"" INR 7,000+",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,Yes,Yes,01: High Priced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08: Premium Cruiser Bike Segment,09: Touring Bike Segment,10: Off Road Bike Segment
4,5,1959-09-08,3.0,KYC Completed,NaN,NaN,400101,Y,M,1.0,Both available,Y,WIFE,Retail5,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,63.0,Retail,Retail,Retail,50705104,5.0,2017-06-12,N,KMFONLINE,10.0,2020-04-13,01D,NaN,N,Distributor,95000.00,200000.00,295000.00,0.32,4.0,2.0,6,5.44,2.61,1.09,Online,NATIONAL DISTRIBUTOR,DIRECT,Equity,Lumpsum,168,Kotak Flexicap Fund,10.0,295000.0,23750.0,25000.0,12.0,14,270000.00,25000.00,NaN,85195.79,55676.27,29519.52,NaN,2.0,2.0,Active,2.0,N,2017-06-12,1.09,Y,NaN,NaN,25000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55676.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.960529,High,NaN,NaN,2.97279,57814.0,303401.94,31.72804,25000.00,0.00,18.07808,270000.00,303401.94,32.99193,NaN,NaN,NaN,0.042276,0.065644,NaN,NaN,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,02: Urban New Wealth,03: SEC A3,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"04: ""Super Premium"" INR 3,500 – 7,000",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,0,Yes,02: Moderate Priced,NaN,02: Premium Scooter Segment,NaN,04: Premium Commuter Segment,05: Entry Level Sports Bike Segment,06: Premium Sports Bike Segment,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,5074,1957-12-11,3.0,KYC Completed,6,Housewife,400053,Y,NaN,NaN,Both available,Y,SON,HNI,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,64.0,Retail,Retail,Retail,NaN,10.0,2017-03-27,N,60922002100,3.0,2022-09-07,267,NaN,N,ITN-eScan,63148250.08,0.00,63148250.08,1.00,16.0,NaN,16,5.65,0.20,0.38,Offline,DIRECT,BANKS,Equity,Lumpsum,144D,Kotak Tax Saver,69.0,63148250.0,3946766.0,NaN,16.0,83,45649000.05,17499250.03,NaN,27125590.34,11710183.80,15415406.54,NaN,12.0,2.0,Active,3.0,N,2017-03-27,0.38,N,44999000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150000.0,NaN,NaN,2500000.0,500000.0,NaN,NaN,NaN,NaN,NaN,NaN,9999500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4999750.0,NaN,NaN,NaN,10746954.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,963229.0,NaN,NaN,NaN,NaN,NaN,NaN,10050783.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5364623.0,NaN,NaN,NaN,1.004792,Low to Moderate,NaN,NaN,1.11467,25701381.0,40634521.95,4.47180,17499250.03,3390738.03,7.46829,47360462.74,37243783.92,3.36463,NaN,NaN,NaN,-0.660822,0.029561,NaN,NaN,Profiled-Urban,"07: High INR 2,30,000 – 3,00,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,01: SEC A1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,0,0,0,Yes,0,0,Yes,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"05: ""Luxury"" INR 7,000+",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,Yes,Yes,01: High Priced,NaN,NaN,NaN,NaN,NaN,06: Premium Sports Bike Segment,NaN,NaN,NaN,NaN
4982,5075,1964-07-01,3.0,KYC Completed,41,Private Sector Service,401602,Y,M,1.0,Both available,Y,WIFE,Retail5,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,OTHERS,58.0,Retail,Retail,Retail,CA12349187,45.0,2018-01-09,S,KMFONLINE,1094.0,2021-09-29,1155,NaN,N,ITN-eScan,0.00,176995.65,176995.65,0.00,NaN,1.0,1,4.87,1.15,NaN,Offline,NATIONAL DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,SIP,168,Kotak Flexicap Fund,66.0,326988.0,NaN,3000.0,59.0,64,326988.15,NaN,NaN,181484.34,181484.34,NaN,NaN,2.0,1.0,Active,2.0,N,2018-01-09,2.72,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159487.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,1.0,3000.0,1.30411,170591.0,221000.00,23.08836,NaN,NaN,NaN,326988.15,221000.00,23.08836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4983,5076,1966-03-07,3.0,KYC Completed,8,Others,400055,Y,M,1.0,Both available,Y,DAUGHTER,Retail,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,56.0,Retail,Retail,Retail,1623703,902.0,2009-09-11,N,KMFONLINE,902.0,2020-10-30,168,NaN,N,Investrak,10000.00,0.00,10000.00,1.00,1.0,NaN,1,13.19,2.06,NaN,Offline,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,178,Kotak Flexicap Fund,2.0,31005.0,10000.0,NaN,1.0,12,31005.09,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,Inactive,1.0,N,2009-09-11,5.62,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.05585,NaN,48124.55,55.21500,NaN,NaN,NaN,31005.09,48124.55,55.21500,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,04: Conservative Urban Middle Class,05: SEC B2,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"04: ""Super Premium"" INR 3,500 – 7,000",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,01: Basic,01: National,0,Yes,02: Moderate Priced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4984,5077,1951-01-07,3.0,KYC Completed,6,Housewife,422105,Y,NaN,NaN,Both available,N,NaN,Retail,Individual,WEST,R.O.M,NASIK,ALL INDIA,T30,Nasik,71.0,Retail,Retail,Retail,11656307,113.0,2021-11-25,N,11656307,113.0,2021-11-25,1155,NaN,N,STP,49997.50,0.00,49997.50,1.00,1.0,NaN,1,0.99,0.99,NaN,Online,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,1155,Kotak Multicap Fund,NaN,49998.0,49998.0,NaN,1.0,1,49997.50,NaN,NaN,53857.10,53857.10,NaN,NaN,1.0,1.0,Active,1.0,N,2021-11-25,1.16,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53857.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,NaN,NaN,0.98099,49998.0,0.00,7.71959,NaN,NaN,NaN,49997.50,0.00,7.71959,NaN,NaN,NaN,0.077637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import sweetviz

In [5]:
df.OCCUPATION_CODE=df.OCCUPATION_CODE.astype(str)
df.FIRST_APPL_NO=df.FIRST_APPL_NO.astype(str)
df.LAST_APPL_NO=df.LAST_APPL_NO.astype(str)
df.LAST_SCH_CODE=df.LAST_SCH_CODE.astype(str)
df["Scheme Code"]=df["Scheme Code"].astype(str)
df["Lifestyle > Smaller Towns"]=df["Lifestyle > Smaller Towns"].astype(str)
df["Special Health Care Target Group"]=df["Special Health Care Target Group"].astype(str)

#df[""]=df[""].astype(str)

list_cols=['Saving Plan','Retirement Plan','Unit Linked Plan','Health','Mutual Fund','Fixed Deposit',\
           'Credit Card Holding','01: Entry Price - Segment INR 2,00,000 – 4,50,000',\
           '02: Entry Premium Hatch Segment INR 4,00,000 – 7,00,000','03: Premium Hatch Segment INR 5,50,000 – 9,00,000',\
           '04: Compact Sedan Segment INR 5,30,000 – 8,50,000','05: Sedan Segment INR 8,00,000 – 13,00,000',\
           '06: Premium Sedan Segment INR 13,00,000 – 20,00,000','07: Compact / Entry SUV Segment INR 9,00,000 – 14,00,000',\
           '08: SUV Segment INR 15,00,000 – 30,00,000','09: Luxury Premium Sedan & SUV Segment INR 25,00,000+',\
           '10: Second-hand Sedan Segment car','11: Second-hand Premium Sedan / SUV Segment',\
           '12: Second-hand Luxury Premium Sedan & SUV Segment','Purchase Price Segment','Laundry > Fabric Wash Products',\
           'Laundry > Washing Machine Products',\
          'Purchase Price Category','Purchase Category > Total','Purchase Category > Gold',\
           'Purchase Category > Diamond','Spend Category','Destination Category','Special Category','Online Shopping Channels',\
           'Product Category Home and Living','01: Entry Level Scooter Segment','02: Premium Scooter Segment',\
           '03: Entry Level Commuter Segment','04: Premium Commuter Segment','05: Entry Level Sports Bike Segment',\
           '06: Premium Sports Bike Segment','07: Entry Level Cruiser Bike Segment','08: Premium Cruiser Bike Segment',\
           '09: Touring Bike Segment','10: Off Road Bike Segment']

for col in list_cols:
    df[col]=df[col].astype(str)

In [6]:
my_report = sweetviz.analyze([df, "Initial Data"],pairwise_analysis="off") #,target_feat='SalePrice'

                                             |                                             | [  0%]   00:00 ->…

C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sweetviz\series_analyzer.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  value_counts_without_nan = pd.Series()
C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sweetviz\series_analyzer.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  value_counts_without_nan = pd.Series()
C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sweetviz\series_analyzer.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  value_counts_without_nan = pd.Series()
C:\Users\user\AppData\Roaming\Python\Python39\site-packages\sweetviz\series_analyzer.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  value_counts_without_nan = pd.Series()

In [7]:
my_report.show_html('Initial_Report.html')

Report Initial_Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [8]:
df.describe(include = 'all')

C:\Users\user\AppData\Local\Temp\ipykernel_2932\4220128335.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include = 'all')
C:\Users\user\AppData\Local\Temp\ipykernel_2932\4220128335.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include = 'all')
C:\Users\user\AppData\Local\Temp\ipykernel_2932\4220128335.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include = 'all')
C:\Users\user\AppData\Local\Temp\ipykernel_2932\4220128335.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include = 'all')

,PAN Key,BIRTH_DATE,FH_KYC,KYC_STATUS_DESC,OCCUPATION_CODE,OCCUPADESC,PINCODE,SMS_ALERT,GENDER,MARITAL_STATUS,CONTACTABILITY,NOMINATION_TAG,NOMINATION_RELATION,SEGMENT,INVTYPDESC,REGION,STATE,BRANCH,MIS_COUNTRY,TOP_T30_B30,CAMS_LOCATION,AGE,RETAIL_FLAG,RETAIL_FLAG_CAMS,INSTITUTIONAL_FLAG,FIRST_APPL_NO,First broker Key,VINTAGE_DATE,FIRST_TRXN_SUBTYPE_CODE,LAST_APPL_NO,Last Broker Key1,LAST_RECENCY_DATE,LAST_SCH_CODE,Last Scheme Name,LAST_TRXN_SUBTYPE_CODE,SOURCE1,LUMPSUM_PURCHASE,SIP_PURCHASE,TOTAL_PURCHASE,LUMPSUM_PROP,NO_OF_LUMPSUM_PURCHASES,NO_OF_SIP_PURCHASES,NO_OF_PURCHASES,VINTAGE,RECENCY,LATENCY,ONLINE_OFFLINE_TAG,FIRST_BROKER_CAT,LAST_BROKER_CAT,FIRST_PRODUCT,FIRST_MODE,Scheme Code,Scheme Name,REDEMPTION_TRXN_COUNT,GROSS_SALES,ATS_LUMPSUM,ATS_SIP,NO_OF_POS_TRXN,NO_OF_TRXN,EQUITY_GS,DEBT_GS,LIQUID_GS,AUM,EQUITY_AUM,DEBT_AUM,LIQUID_AUM,NO_OF_SCHEMES,NO_OF_ASSET_CLASS,STATUS,NO_OF_CHANNEL,PPD_STATUS,ACQUISITION_DATE,LATENCY_CLEAN,REGISTERED_ONLINE,ARBITRAGE_FUND_GS,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_GS,BANKING_AND_PSU_FUND_GS,CAPITAL_PROTECTION_ORIENTED_SCHEMES_GS,CONSERVATIVE_HYBRID_FUND_GS,CORPORATE_BOND_FUND_GS,CREDIT_RISK_FUND_GS,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_GS,DYNAMIC_BOND_FUND_GS,ELSS_GS,EQUITY_OTHERS_C_GS,EQUITY_SAVINGS_FUND_GS,FIXED_TERM_PLAN_GS,FLEXI_CAP_FUND_GS,FLOATER_FUND_GS,FOCUSED_FUND_GS,FUND_OF_FUND_DOMESTIC_GS,FUND_OF_FUND_OVERSEAS_GS,GILT_FUND_GS,GOLD_ETFS_GS,INDEX_FUNDS_DEBT_GS,INDEX_FUNDS_EQUITY_GS,LARGE_MID_CAP_FUND_GS,LARGE_CAP_FUND_GS,LIQUID_FUND_GS,LOW_DURATION_FUND_GS,MEDIUM_DURATION_FUND_GS,MEDIUM_TO_LONG_DURATION_FUND_GS,MID_CAP_FUND_GS,MONEY_MARKET_FUND_GS,MULTI_CAP_FUND_GS,OTHER_ETFS_GS,OVERNIGHT_FUND_GS,SECTORAL_THEMATIC_FUNDS_GS,SHORT_DURATION_FUND_GS,SMALL_CAP_FUND_GS,ULTRA_SHORT_DURATION_FUND_GS,VALUE_FUND_CONTRA_FUND_GS,ARBITRAGE_FUND_AUM,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_AUM,BANKING_AND_PSU_FUND_AUM,CAPITAL_PROTECTION_ORIENTED_SCHEMES_AUM,CONSERVATIVE_HYBRID_FUND_AUM,CORPORATE_BOND_FUND_AUM,CREDIT_RISK_FUND_AUM,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_AUM,DYNAMIC_BOND_FUND_AUM,ELSS_AUM,EQUITY_OTHERS_C_AUM,EQUITY_SAVINGS_FUND_AUM,FIXED_TERM_PLAN_AUM,FLEXI_CAP_FUND_AUM,FLOATER_FUND_AUM,FOCUSED_FUND_AUM,FUND_OF_FUND_DOMESTIC_AUM,FUND_OF_FUND_OVERSEAS_AUM,GILT_FUND_AUM,GOLD_ETFS_AUM,INDEX_FUNDS_DEBT_AUM,INDEX_FUNDS_EQUITY_AUM,LARGE_MID_CAP_FUND_AUM,LARGE_CAP_FUND_AUM,LIQUID_FUND_AUM,LOW_DURATION_FUND_AUM,MEDIUM_DURATION_FUND_AUM,MEDIUM_TO_LONG_DURATION_FUND_AUM,MID_CAP_FUND_AUM,MONEY_MARKET_FUND_AUM,MULTI_CAP_FUND_AUM,OTHER_ETFS_AUM,OVERNIGHT_FUND_AUM,SECTORAL_THEMATIC_FUNDS_AUM,SHORT_DURATION_FUND_AUM,SMALL_CAP_FUND_AUM,ULTRA_SHORT_DURATION_FUND_AUM,VALUE_FUND_CONTRA_FUND_AUM,RISK_VALUE,RISK_APPETITE,LIVE_SIP,ATS_SIP_LIVE,AHT,COST_VALUE,NEGATIVE_AMT,ABS_RETURNS,POSITIVE_AMT_DEBT,NEGATIVE_AMT_DEBT,ABS_RETURNS_DEBT,POSITIVE_AMT_EQUITY,NEGATIVE_AMT_EQUITY,ABS_RETURNS_EQUITY,POSITIVE_AMT_LIQUID,NEGATIVE_AMT_LIQUID,ABS_RETURNS_LIQUID,XIRR_EQUITY,XIRR_DEBT,XIRR_LIQUID,XIRR,Profiling status,Income,Urban,Lifestyle,SEC Reference,Lifestyle > Smaller Towns,Special Health Care Target Group,Saving Plan,Retirement Plan,Unit Linked Plan,Health,Mutual Fund,Fixed Deposit,Credit Card Holding,"01: Entry Price - Segment INR 2,00,000 – 4,50,000","02: Entry Premium Hatch Segment INR 4,00,000 – 7,00,000","03: Premium Hatch Segment INR 5,50,000 – 9,00,000","04: Compact Sedan Segment INR 5,30,000 – 8,50,000","05: Sedan Segment INR 8,00,000 – 13,00,000","06: Premium Sedan Segment INR 13,00,000 – 20,00,000","07: Compact / Entry SUV Segment INR 9,00,000 – 14,00,000","08: SUV Segment INR 15,00,000 – 30,00,000","09: Luxury Premium Sedan & SUV Segment INR 25,00,000+",10: Second-hand Sedan Segment car,11: Second-hand Premium Sedan / SUV Segment,12: Second-hand Luxury Premium Sedan & SUV Segment,Purchase Price Segment,Laundry > Fabric Wash Products,Laundry > Washing Machine Products,Personal Wash,Packaged Food,Cosmetics,Purchase Price Category,Purchase Category > Total,Purchase Category > Gold,Purchase Category > Diamond,Spend Category,Destination Category,Special Category,Online Shopping Channels,Product Category Home and Living,01: Entry Level Scooter Segment,02: Premium Scooter Segment,03: Entry Level Commuter Segment,04: Premium Commuter Segment,05: Entry Level Sports Bike Segment,06: Premium Sports Bike Segment,07: Entry Level Cruiser Bike Segment,08: Premium Cruiser Bike Segment,09: Touring Bike Segment,10: Off Road Bike Segment
count,4986.000000,4829,3971.000000,3917,4986,3989,4986.000000,4202,3338,3084.000000,4986,4986,2735,4986,4986,4983,4983,4983,4983,4983,4983,4829.000000,4986,4986,4986,4986,4900.000000,4899,4899,4986,4953.000000,4953,4986,0.0,4953,4846,4.986000e+03,4.986000e+03,4.986000e+03,4899.000000,3323.000000,3010.000000,4986.000000,4899.000000,4953.000000,3124.000000,4691,4890,4934,4787,4986,4986,4842,2567.000000,4.901000e+03,3.323000e+03,3010.000000,4899.000000,4986.000000,4.624000e+03,1.153000e+03,3.050000e+02,4.048000e+03,3.809000e+03,6.040000e+02,8.700000e+01,4901.000000,4901.000000,4986,4981.000000,4986,4986,4959.000000,4986,2.290000e+02,1.920000e+02,5.800000e+01,6.000000e+00,5.300000e+01,6.700000e+01,7.200000e+01,3.620000e+02,8.600000e+01,458.000000,3.400000e+01,9.000000e+01,7.600000e+01,2.585000e+03,1.600000e+01,1.260000e+02,1.980000e+02,2.600000e+02,3.400000e+01,0.0,1.000000e+01,5.300000e+01,6.230000e+02,4.740000e+02,2.850000e+02,3.190000e+02,6.200000e+01,5.500000e+01,1.302000e+03,6.200000e+01,2.320000e+02,7.000000e+00,3.900000e+01,5.340000e+02,6.500000e+01,5.050000e+02,1.910000e+02,9.700000e+01,9.900000e+01,1.240000e+02,2.300000e+01,0.0,2.900000e+01,3.800000e+01,2.300000e+01,2.870000e+02,2.900000e+01,3.440000e+02,4.000000e+00,4.700000e+01,1.0,1.883000e+03,1.000000e+01,1.000000e+02,1.040000e+02,1.900000e+02,1.000000e+01,0.0,1.000000e+01,4.000000e+01,4.390000e+02,3.140000e+02,8.400000e+01,1.090000e+02,2.200000e+01,1.400000e+01,1.075000e+03,2.100000e+01,2.170000e+02,2.000000e+00,5.000000e+00,2.620000e+02,2.800000e+01,3.770000e+02,5.000000e+01,5.100000e+01,3818.000000,3818,1989.000000,1989.000000,4986.000000,4.114000e+03,4.986000e+03,4958.000000,1.170000e+03,1.170000e+03,1166.000000,4.717000e+03,4.717000e+03,4687.000000,3.070000e+02,3.070000e+02,307.000000,4270.000000,1069.000000,272.000000,959.000000,4129,4129,4129,4129,4129,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4129,4129,4129,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986,4986
unique,NaN,4179,NaN,3,24,19,NaN,2,2,NaN,4,2,41,8,14,5,8,11,1,2,12,NaN,2,2,2,2580,NaN,1951,2,1412,NaN,1503,176,NaN,2,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,9,9,3,2,190,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,1989,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,4,6,8,4,4,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,3,3,3,6,4,3,3,2,3,6,4,4,4,4,4,3,3,4,2,2,2,2,2,2,2,2,2,2
top,NaN,1977-06-01 00:00:00,NaN,KYC Completed,nan,Private Sector Service,NaN,Y,M,NaN,Both available,Y,NOT PROVIDED,Retail,Individual,BBY,MUMBAI,MUMBAI,ALL INDIA,T30,Mumbai,NaN,Retail,Retail,Retail,nan,NaN,2008-01-25 00:00:00,N,nan,NaN,2011-09-09 00:00:00,168,NaN,N,ITN-eScan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Offline,NATIONAL DISTRIBUTOR,NATIONAL DISTRIBUTOR,Equity,Lumpsum,168,Kotak Flexicap Fund,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Active,NaN,N,2008-01-25 00:00:00,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very High,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Profiled-Urban,"04: Medium Good INR 80,000 – 1,30,000",01: Cosmopolitan Urban Area,02: Urban New Wealth,03: SEC A3,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,0,0,0,0,0,0,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"03: ""Premium"" INR 1,500 – 3,500",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,01: Basic,01: National,0,Yes,02: Moderate Priced,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
freq,NaN,6,NaN,3895,992,916,NaN,4096,2083,NaN,3943,3245,772,2590,4807,2631,2631,2631,4983,4981,1626,NaN,4972,4926,4940,2157,NaN,103,2488,3188,NaN,66,1224,NaN,2948,1721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2377,2345,2236,4161,2575,1633,1876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4029,NaN,4732,105,NaN,4326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4129,1337,2188,1216,1223,3569,3235,3889,3769,3633,3988,2536,3175,3054,3960,3960,2532,2769,2970,3642,2970,3642,3527,3170,2483,3527,2049,3472,4034,3299,3794,2190,1796,3726,3086,2333,2287,2287,3101,3788,2754,4606,4047,4500,3750,3993,3313,4575,4775,4775,4775
first,NaN,1925-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998-12-29 00:00:00,NaN,NaN,NaN,2000-04-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998-12-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,2022-04-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-11-01 00:00:00,NaN,NaN,NaN,2022-11-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2531.604894,NaN,3.002770,NaN,NaN,NaN,407608.293823,NaN,NaN,1.189689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.118451,NaN,NaN,NaN,NaN,151.765510,NaN,NaN,NaN,177.246315,NaN,NaN,NaN,NaN,NaN,2.125988e+08,1.285376e+05,2.127273e+08,0.522948,8.029190,2.345183,6.766947,6.350882,3.030046,3.127554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.349046,2.180888e+08,1.279113e+06,5631.116279,38.224944,63.880465,4.802412e+06,1.812765e+07,1.328014e+08,4.385519e+06,4.347190e+06,1.732550e+06,1.608686e+06,2.214854,1.240971,NaN,1.244529,NaN,NaN,2.982311,NaN,1.517467e+07,9.839282e+05,7.593372e+06,1.591768e+06,4.908016e+05,5.824584e+05,1.392485e+06,1.017623e+06,4.860332e+07,62144.921397,9.546432e+05,1.272766e+06,2.436076e+07,5.925393e+05,2.151941e+07,3.729224e+05,3.324093e+05,2.854115e+05,1.236053e+06,NaN,1.075851e+07,2.400285e+05,4.740997e+05,2.228929e+05,8.700706e+07,4.316138e+06,4.092623e+06,2.851866e+06,4.536243e+05,4.481760e+07,2.307345e+05,2.149374e+09,4.027541e+08,3.436421e+05,2.732404e+06,2.311104e+05,4.647604e+07,1.666897e+05,3.962022e+06,2.699621e+05,2.910492e+06,NaN,3.204098e+05,6.954418e+05,1.255745e+06,1.317349e+06,8.424639e+05,1.008328e+05,1.161500e+06,1.359737e+06,51863.0,6.130814e+05,1.795182e+07,4.775429e+05,3.259496e+05,2.337605e+05,7.696891e+05,NaN,1.093053e+07,1.769215e+05,7.401849e+05,3.253969e+05,1.422319e+06,4.555470e+05,3.888706e+06,3.269832e+05,5.344521e+05,8.883309e+06,2.462118e+05,6.563763e+09,4.096184e+06,5.161966e+05,4.022624e+06,3.037918e+05,1.532687e+06,1.915617e+05,5.497365,NaN,1.518854,4919.379085,2.922642,3.274654e+06,2.150464e+08,44.064270,4.275655e+08,4.279602e+08,16.238210,5.518537e+06,3.302330e+06,48.041472,1.125878e+09,1.125916e+09,2.897618,0.072711,0.019397,-0.051750,-0.000610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1466.661631,NaN,0.187096,NaN,NaN,NaN,17488.604350,NaN,NaN,0.392118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.586330,NaN,NaN,NaN,NaN,213.675279,NaN,NaN,NaN,265.314791,NaN,NaN,NaN,NaN,NaN,8.693812e+09,4.868111e+05,8.693810e+09,0.454738,38.167492,6.788510,33.531940,4.828132,3.338129,3.719302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218.177094,8.770623e+09,3.256948e+07,29835.633509,109.318741,236.769866,1.544348e+08,2.116577e+08,1.434559e+09,1.461126e+08,1.504935e+08,1.098523e+07,6.725611e+06,2.227690,0.502730,NaN,0.537016,NaN,NaN,3.155659,NaN,8.432799e+07,8.758066e+06,3.263641e+07,2.243092e+06,1.503473e+06,8.510413e+05,3.182378e+06,4.265298e+06,3.330737e+08,89821.692763,3.469882e+06,2.322510e+06,1.032008e+08,4.976064e+06,4.674985e+07,2.098153e+06,1.330795e+06,9.805768e+05,2.358145e+06,NaN,2.298691e+07,9.896434e+05,2.969863e+06,9.237639e+05,8.509820e+08,4.006003e+07,1.450363e+07,6.442207e+06,4.114744e+06,2.094128e+08,6.538091e+05,3.557227e+09,1.714464e+09,1.659179e+06,1.039907e+07,7.463180e+05,2.938681e+08,5.417660e+05,1.274284e+07,3.220732e+05,5.950221e+06,NaN,4.356430e+05,1.052497e+06,2.049688e+06,5.437249e+06,2.104501e+06,1.293063e+05,1.284197e+06,2.562561e+06,NaN,3.993107e+06,4.349963e+07,2.622668e+06,1.058584e+06,8.720721e+05,1.962008e+06,NaN,2.342046e+07,6.368258e+05,4.066273e+06,1.265992e+06,6.391313e+06,9.601463e+05,1.063766e+07,4.318512e+05,3.280823e+06,2.847050e+07,7.176587e+05,0.000000e+00,8.260131e+06,1.830584e+06,1.481000e+07,1.034402e+06,7.091669e+06,2.815159e+05,1.190391,NaN,1.360654,25301.420918,2.909766,9.624802e+07,8.676934e+09,86.902491,9.724959e+09,9.728393e+09,86.271223,1.750100e+08,9.092972e+07,85.853111,1.356548e+10,1.356987e+10,4.598573,0.496994,1.596366,0.196324,0.028138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,1.000000,NaN,NaN,NaN,40143.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000,1.000000,0.000000,0.050000,0.000000,0.010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000e+00,0.000000e+00,-10999.000000,1.000000,1.000000,0.000000e+00,0.000000e+00,2.160000e+00,2.000000e-02,1.600000e-01,2.000000e-02,2.450000e+00,0.000000,0.000000,NaN,1.000000,NaN,NaN,0.010000,NaN,0.000000e+00,0.000000e+00,6.000000e+03,1.500000e+05,0.000000e+00,5.000000e+03,0.000000e+00,0.000000e+00,3.000000e+03,0.000000,5.000000e+03,0.000000e+00,2.500000e+04,0.000000e+00,1.000000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,1.502400e+04,1.000000e+02,0.000000e+00,0.000000e+00,2.000000e+00,1.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+03,5.000000e+02,5.000000e+03,5.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+03,0.000000e+00,5.000000e+00,1.046000e+04,NaN,2.293000e+03,6.100000e+01,0.000000e+00,2.000000e+00,1.500000e+01,6.400000e+01,1.010000e+05,9.012000e+03,51863.0,0.000000e+00,2.260670e+05,1.008000e+03,1.568000e+03,3.000000e+00,7.152000e+03,NaN,1.502700e+04,1.170000e+02,1.000000e+00,9.900000e+01,2.000000e+00,5.600000e+01,2.755800e+04,3.000000e+00,9.000000e+00,1.000000e+02,5.320000e+02,6.563763e+09,1.792740e+05,1.508000e+03,1.041600e+04,2.600000e+01,3.640000e+02,1.004000e+03,0.009433,NaN,1.000000,100.000000,0.000030,0.000000e+00,0.000000e+00,-61.638000,0.000000e+00,0.000000e+00,-41.471560,0.000000e+00,0.000000e+00,-100.000000,2.160000e+00,0.000000e+00,-0.305410,-1.000000,-0.999931,-0.996155,-0.597735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1252.250000,NaN,3.000000,NaN,NaN,NaN,400097.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,2.800000e+04,0.000000,1.000000,1.000000,1.000000,3.485000,0.720000,0.727500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,3.500000e+04,9.065500e+03,1000.000000,2.000000,6.000000,3.246242e+04,4.319937e+04,9.999500e+04,3.210283e+04,3.268368e+04,2.011752e+04,4.959740e+03,1.000000,1.000000,NaN,1.000000,NaN,NaN,1.160000,NaN,1.499930e+05,4.717350e+04,6.524925e+04,2.498500e+05,3.000000e+04,4.999800e+04,1.464368e+05,4.199800e+04,6.524675e+04,10000.000000,3.447500e+04,6.374975e+04,3.500000e+05,3.500000e+04,5.837208e+05,2.522500e+04,2.000000e+04,1.346400e+04,2.875000e+04,NaN,9.817805e+05,2.000000e+03,2.499900e+04,1.202250e+04,9.610000e+04,9.999500e+04,1.000000e+05,9.990000e+04,2.300000e+04,1.101078e+05,1.499900e+04,3.499900e+04,1.484965e+05,1.000000e+04,6.000000e+04,1.299900e+04,9.999500e+04,1.500000e+04,5.298650e+04,5.357200e+04,6.293450e+04,NaN,3.698200e+04,5.670200e+04,2.332065e+05,4.661200e+04,5.453200e+04,1.908300e+04,5.555000e+05,6.812000e+04,51863.0,3.936800e+04,9.811552e+05,3.535975e+04,2.025200e+04,1.190400e+04,1.751275e+04,NaN,9.966180e+05,5.232250e+03,4.088500e+04,1.387900e+04,4.736750e+03,3.018900e+04,2.440120e+05,2.774025e+04,2.244200e+04,4.923000e+04,1.606200e+04,6.563763e+09,3.114960e+05,2.951200e+04,5.899475e+04,1.552400e+04,1.693600e+04,3.602550e+04,6.000000,NaN,1.000000,1000.000000,1.096900,2.274175e+04,0.000000e+00,8.374478,4.441160e+04,5.348243e+03,0.833202,3.200000e+04,0.000000e+00,10.165845,9.999500e+04,5.419841e+04,0.417305,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.drop(['BIRTH_DATE', 'FH_KYC','KYC_STATUS_DESC','PINCODE','SMS_ALERT','Scheme Code', 'MARITAL_STATUS','CONTACTABILITY','NOMINATION_TAG','NOMINATION_RELATION','REGION','STATE','BRANCH','MIS_COUNTRY','CAMS_LOCATION','FIRST_APPL_NO','First broker Key','LAST_APPL_NO','Last Broker Key1','LAST_SCH_CODE' , 'Last Scheme Name' , 'LAST_TRXN_SUBTYPE_CODE' , 'REDEMPTION_TRXN_COUNT' , 'ACQUISITION_DATE'], axis=1, inplace=True)

In [10]:
df

,PAN Key,OCCUPATION_CODE,OCCUPADESC,GENDER,SEGMENT,INVTYPDESC,TOP_T30_B30,AGE,RETAIL_FLAG,RETAIL_FLAG_CAMS,INSTITUTIONAL_FLAG,VINTAGE_DATE,FIRST_TRXN_SUBTYPE_CODE,LAST_RECENCY_DATE,SOURCE1,LUMPSUM_PURCHASE,SIP_PURCHASE,TOTAL_PURCHASE,LUMPSUM_PROP,NO_OF_LUMPSUM_PURCHASES,NO_OF_SIP_PURCHASES,NO_OF_PURCHASES,VINTAGE,RECENCY,LATENCY,ONLINE_OFFLINE_TAG,FIRST_BROKER_CAT,LAST_BROKER_CAT,FIRST_PRODUCT,FIRST_MODE,Scheme Name,GROSS_SALES,ATS_LUMPSUM,ATS_SIP,NO_OF_POS_TRXN,NO_OF_TRXN,EQUITY_GS,DEBT_GS,LIQUID_GS,AUM,EQUITY_AUM,DEBT_AUM,LIQUID_AUM,NO_OF_SCHEMES,NO_OF_ASSET_CLASS,STATUS,NO_OF_CHANNEL,PPD_STATUS,LATENCY_CLEAN,REGISTERED_ONLINE,ARBITRAGE_FUND_GS,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_GS,BANKING_AND_PSU_FUND_GS,CAPITAL_PROTECTION_ORIENTED_SCHEMES_GS,CONSERVATIVE_HYBRID_FUND_GS,CORPORATE_BOND_FUND_GS,CREDIT_RISK_FUND_GS,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_GS,DYNAMIC_BOND_FUND_GS,ELSS_GS,EQUITY_OTHERS_C_GS,EQUITY_SAVINGS_FUND_GS,FIXED_TERM_PLAN_GS,FLEXI_CAP_FUND_GS,FLOATER_FUND_GS,FOCUSED_FUND_GS,FUND_OF_FUND_DOMESTIC_GS,FUND_OF_FUND_OVERSEAS_GS,GILT_FUND_GS,GOLD_ETFS_GS,INDEX_FUNDS_DEBT_GS,INDEX_FUNDS_EQUITY_GS,LARGE_MID_CAP_FUND_GS,LARGE_CAP_FUND_GS,LIQUID_FUND_GS,LOW_DURATION_FUND_GS,MEDIUM_DURATION_FUND_GS,MEDIUM_TO_LONG_DURATION_FUND_GS,MID_CAP_FUND_GS,MONEY_MARKET_FUND_GS,MULTI_CAP_FUND_GS,OTHER_ETFS_GS,OVERNIGHT_FUND_GS,SECTORAL_THEMATIC_FUNDS_GS,SHORT_DURATION_FUND_GS,SMALL_CAP_FUND_GS,ULTRA_SHORT_DURATION_FUND_GS,VALUE_FUND_CONTRA_FUND_GS,ARBITRAGE_FUND_AUM,BALANCED_HYBRID_FUND_AGGRESSIVE_HYBRID_FUND_AUM,BANKING_AND_PSU_FUND_AUM,CAPITAL_PROTECTION_ORIENTED_SCHEMES_AUM,CONSERVATIVE_HYBRID_FUND_AUM,CORPORATE_BOND_FUND_AUM,CREDIT_RISK_FUND_AUM,DYNAMIC_ASSET_ALLOCATION_BALANCED_ADVANTAGE_AUM,DYNAMIC_BOND_FUND_AUM,ELSS_AUM,EQUITY_OTHERS_C_AUM,EQUITY_SAVINGS_FUND_AUM,FIXED_TERM_PLAN_AUM,FLEXI_CAP_FUND_AUM,FLOATER_FUND_AUM,FOCUSED_FUND_AUM,FUND_OF_FUND_DOMESTIC_AUM,FUND_OF_FUND_OVERSEAS_AUM,GILT_FUND_AUM,GOLD_ETFS_AUM,INDEX_FUNDS_DEBT_AUM,INDEX_FUNDS_EQUITY_AUM,LARGE_MID_CAP_FUND_AUM,LARGE_CAP_FUND_AUM,LIQUID_FUND_AUM,LOW_DURATION_FUND_AUM,MEDIUM_DURATION_FUND_AUM,MEDIUM_TO_LONG_DURATION_FUND_AUM,MID_CAP_FUND_AUM,MONEY_MARKET_FUND_AUM,MULTI_CAP_FUND_AUM,OTHER_ETFS_AUM,OVERNIGHT_FUND_AUM,SECTORAL_THEMATIC_FUNDS_AUM,SHORT_DURATION_FUND_AUM,SMALL_CAP_FUND_AUM,ULTRA_SHORT_DURATION_FUND_AUM,VALUE_FUND_CONTRA_FUND_AUM,RISK_VALUE,RISK_APPETITE,LIVE_SIP,ATS_SIP_LIVE,AHT,COST_VALUE,NEGATIVE_AMT,ABS_RETURNS,POSITIVE_AMT_DEBT,NEGATIVE_AMT_DEBT,ABS_RETURNS_DEBT,POSITIVE_AMT_EQUITY,NEGATIVE_AMT_EQUITY,ABS_RETURNS_EQUITY,POSITIVE_AMT_LIQUID,NEGATIVE_AMT_LIQUID,ABS_RETURNS_LIQUID,XIRR_EQUITY,XIRR_DEBT,XIRR_LIQUID,XIRR,Profiling status,Income,Urban,Lifestyle,SEC Reference,Lifestyle > Smaller Towns,Special Health Care Target Group,Saving Plan,Retirement Plan,Unit Linked Plan,Health,Mutual Fund,Fixed Deposit,Credit Card Holding,"01: Entry Price - Segment INR 2,00,000 – 4,50,000","02: Entry Premium Hatch Segment INR 4,00,000 – 7,00,000","03: Premium Hatch Segment INR 5,50,000 – 9,00,000","04: Compact Sedan Segment INR 5,30,000 – 8,50,000","05: Sedan Segment INR 8,00,000 – 13,00,000","06: Premium Sedan Segment INR 13,00,000 – 20,00,000","07: Compact / Entry SUV Segment INR 9,00,000 – 14,00,000","08: SUV Segment INR 15,00,000 – 30,00,000","09: Luxury Premium Sedan & SUV Segment INR 25,00,000+",10: Second-hand Sedan Segment car,11: Second-hand Premium Sedan / SUV Segment,12: Second-hand Luxury Premium Sedan & SUV Segment,Purchase Price Segment,Laundry > Fabric Wash Products,Laundry > Washing Machine Products,Personal Wash,Packaged Food,Cosmetics,Purchase Price Category,Purchase Category > Total,Purchase Category > Gold,Purchase Category > Diamond,Spend Category,Destination Category,Special Category,Online Shopping Channels,Product Category Home and Living,01: Entry Level Scooter Segment,02: Premium Scooter Segment,03: Entry Level Commuter Segment,04: Premium Commuter Segment,05: Entry Level Sports Bike Segment,06: Premium Sports Bike Segment,07: Entry Level Cruiser Bike Segment,08: Premium Cruiser Bike Segment,09: Touring Bike Segment,10: Off Road Bike Segment
0,1,nan,NaN,NaN,Domestic Corp,Body Corporate,T30,NaN,Institutional,Institutional,Insti,2017-10-24,N,2021-01-14,ITN-eScan,5000000.00,0.00,5000000.00,1.00,1.0,NaN,1,5.08,1.85,NaN,Offline,CORPORATE DISTRIBUTOR,CORPORATE DISTRIBUTOR,Debt,Lumpsum,Kotak Medium Term Fund,11165243.0,5000000.0,NaN,1.0,3,NaN,11165243.06,NaN,6584041.19,NaN,6584041.19,NaN,2.0,1.0,Active,1.0,N,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6165243.0,5000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6584041.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,Moderate,NaN,NaN,3.21546,6165242.0,6165551.32,14.19001,11165243.06,6165551.32,14.19001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.036014,NaN,NaN,Profiled-Urban,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,03: Aspiring Urban Middle Class,04: SEC B1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,0,Yes,0,0,02: Expected Moderate / Average Use,0,0,Yes,Yes,0,0,0,0,0,0,0,0,"03: INR 51,00,000 - 1 Crore",01: Mass Fabric Products,Yes,02: Popular Classified Products,02: Premium Classified Products,02: Popular Classified Products,"02: “Medium"" INR 800 – 1,500",01: Branded Jewellery,03: Moderately priced Gold Jewellery,05: Moderately priced Diamond Jewellery,01: Basic,01: National,0,Yes,02: Moderate Priced,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,2,1,Business,NaN,Domestic Corp,Public Limited Company,T30,NaN,Retail,Institutional,Insti,2018-01-04,N,2022-08-22,eISC,6299860.00,1599920.00,7899780.00,0.79,3.0,1.0,4,4.88,0.25,1.63,Offline,MUTUAL FUND DISTRIBUTOR,NATIONAL DISTRIBUTOR,NaN,Lumpsum,NaN,18195798.0,2099953.0,399980.0,9.0,915,8192419.07,NaN,4503478.63,11783596.42,11783596.42,NaN,NaN,3.0,2.0,Active,2.0,N,1.63,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5792539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2399880.0,NaN,4503479.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9314442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2469155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,1.0,400000.0,3.36743,8192419.0,10296017.70,19.42334,NaN,NaN,NaN,8192419.07,0.00,43.83537,4692627.84,4692539.07,-0.00189,0.122454,NaN,0.00000,NaN,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,02: SEC A2,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,02: Popular Classified Products,"03: ""Premium"" INR 1,500 – 3,500",01: Branded Jewellery,04: High priced Gold Jewellery,0,01: Basic,01: National,0,Yes,02: Moderate Priced,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,3,8,Others,NaN,Domestic Corp,Body Corporate,T30,NaN,Retail,Institutional,Insti,2017-09-18,N,2022-09-28,Distributor,9859525.01,0.00,9859525.01,1.00,11.0,NaN,11,5.18,0.15,0.52,Online,BANKS,BANKS,NaN,Lumpsum,NaN,11577903.0,896320.0,NaN,11.0,385,10514245.16,503668.30,199990.00,10066215.93,9687882.54,343482.83,34850.57,11.0,3.0,Active,2.0,N,0.52,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4499775.0,NaN,NaN,500000.0,NaN,NaN,860000.0,NaN,999900.0,NaN,499975.0,NaN,NaN,NaN,NaN,NaN,166652.0,199990.0,NaN,NaN,NaN,NaN,3693.0,299985.0,NaN,NaN,3187933.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4898453.0,NaN,NaN,NaN,NaN,NaN,848034.0,NaN,NaN,NaN,343483.0,NaN,NaN,NaN,NaN,NaN,169139.0,34851.0,NaN,NaN,NaN,NaN,NaN,318974.0,NaN,NaN,3453283.0,NaN,NaN,NaN,NaN,1.858751,Low to Moderate,NaN,NaN,1.19710,9188754.0,2940795.74,12.30644,503785.23,3859.73,-31.05345,10514245.16,2406582.71,15.02933,199990.00,166660.00,0.76032,0.067900,-0.247453,NaN,NaN,Profiled-Urban,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,05: Successful Urban Fast Climbers,06: SEC C1,0,02: Health Care - ‘The Carefree / Anxious’ In ...,01: Saving Plan,Yes,0,Yes,0,0,0,0,0,Yes,Yes,0,0,0,0,0,0,0,0,"03: INR 51,00,000 - 1 Crore",01: Mass Fabric Products,Yes,02: Popular Classified Products,01: Mass Classified Products,02: Popular Classified Products,"02: “Medium"" INR 800 – 1,500",02: Traditional / Non-branded Jewellery,03: Moderately priced Gold Jewellery,05: Moderately priced Diamond Jewellery,01: Basic,01: National,0,0,02: Moderate Priced,01: Entry Level Scooter Segment,nan,03: Entry Level Commuter Segment,nan,nan,nan,nan,nan,nan,nan
3,4,3,Professional,M,HNI,Individual,T30,66.0,Retail,Retail,Retail,2015-07-17,N,2022-10-25,ITN-eScan,52348080.10,0.00,52348080.10,1.00,13.0,NaN,13,7.34,0.07,0.61,Offline,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,Kotak Equity Saving Fund,67868914.0,4026775.0,NaN,13.0,57,27670739.32,3700000.00,36498175.10,27936316.97,26839053.64,NaN,1097263.33,10.0,3.0,Active,1.0,N,0.61,N,NaN,NaN,NaN,NaN,NaN,NaN,3700000.0,1499925.0,NaN,NaN,NaN,8738804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3399830.0,7532306.0,36498175.0,NaN,NaN,NaN,4000000.0,NaN,NaN,NaN,NaN,2499875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1532678.0,NaN,NaN,NaN,5317325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3634823.0,5698805.0,1097263.0,NaN,NaN,NaN,7652323.0,NaN,NaN,NaN,NaN,3003100.0,NaN,NaN,NaN,NaN,4.942699,High,NaN,NaN,3.05478,22496618.0,48213020.49,12.20061,3700000.00,4691410.15,26.79487,27670739.32,7521610.34,24.17689,36498175.10,36000000.00,1.64142,0.126981,0.000000,-0.02874,NaN,Profiled-Urban,"08: Very High INR > 3,00,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,01: SEC A1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,0,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,0,0,0,Yes,0,0,Yes,05: Beyond INR 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"05: ""Luxury"" INR 7,000+",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,Yes,Yes,01: High Priced,nan,nan,nan,nan,nan,nan,nan,08: Premium Cruiser Bike Segment,09: Touring Bike Segment,10: Off Road Bike Segment
4,5,nan,NaN,M,Retail5,Individual,T30,63.0,Retail,Retail,Retail,2017-06-12,N,2020-04-13,Distributor,95000.00,200000.00,295000.00,0.32,4.0,2.0,6,5.44,2.61,1.09,Online,NATIONAL DISTRIBUTOR,DIRECT,Equity,Lumpsum,Kotak Flexicap Fund,295000.0,23750.0,25000.0,12.0,14,270000.00,25000.00,NaN,85195.79,55676.27,29519.52,NaN,2.0,2.0,Active,2.0,N,1.09,Y,NaN,NaN,25000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55676.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.960529,High,NaN,NaN,2.97279,57814.0,303401.94,31.72804,25000.00,0.00,18.07808,270000.00,303401.94,32.99193,NaN,NaN,NaN,0.042276,0.065644,NaN,NaN,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,02: Urban New Wealth,03: SEC A3,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"04: ""Super Premium"" INR 3,500 – 7,000",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,0,Yes,02: Moderate Priced,nan,02: Premium Scooter Segment,nan,04: Premium Commuter Segment,05: Entry Level Sports Bike Segment,06: Premium Sports Bike Segment,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,5074,6,Housewife,NaN,HNI,Individual,T30,64.0,Retail,Retail,Retail,2017-03-27,N,2022-09-07,ITN-eScan,63148250.08,0.00,63148250.08,1.00,16.0,NaN,16,5.65,0.20,0.38,Offline,DIRECT,BANKS,Equity,Lumpsum,Kotak Tax Saver,63148250.0,3946766.0,NaN,16.0,83,45649000.05,17499250.03,NaN,27125590.34,11710183.80,15415406.54,NaN,12.0,2.0,Active,3.0,N,0.38,N,44999000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150000.0,NaN,NaN,2500000.0,500000.0,NaN,NaN,NaN,NaN,NaN,NaN,9999500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4999750.0,NaN,NaN,NaN,10746954.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,963229.0,NaN,NaN,NaN,NaN,NaN,NaN,10050783.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5364623.0,NaN,NaN,NaN,1.004792,Low to Moderate,NaN,NaN,1.11467,25701381.0,40634521.95,4.47180,17499250.03,3390738.03,7.46829,47360462.74,37243783.92,3.36463,NaN,NaN,NaN,-0.660822,0.029561,NaN,NaN,Profiled-Urban,"07: High INR 2,30,000 – 3,00,000",01: Cosmopolitan Urban Area,01: Urban Established Elite,01: SEC A1,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,0,0,0,Yes,0,0,Yes,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"05: ""Luxury"" INR 7,000+",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,Yes,Yes,01: High Priced,nan,nan,nan,nan,nan,06: Premium Sports Bike Segment,nan,nan,nan,nan
4982,5075,41,Private Sector Service,M,Retail5,Individual,T30,58.0,Retail,Retail,Retail,2018-01-09,S,2021-09-29,ITN-eScan,0.00,176995.65,176995.65,0.00,NaN,1.0,1,4.87,1.15,NaN,Offline,NATIONAL DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,SIP,Kotak Flexicap Fund,326988.0,NaN,3000.0,59.0,64,326988.15,NaN,NaN,181484.34,181484.34,NaN,NaN,2.0,1.0,Active,2.0,N,2.72,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159487.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,1.0,3000.0,1.30411,170591.0,221000.00,23.08836,NaN,NaN,NaN,326988.15,221000.00,23.08836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4983,5076,8,Others,M,Retail,Individual,T30,56.0,Retail,Retail,Retail,2009-09-11,N,2020-10-30,Investrak,10000.00,0.00,10000.00,1.00,1.0,NaN,1,13.19,2.06,NaN,Offline,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,Kotak Flexicap Fund,31005.0,10000.0,NaN,1.0,12,31005.09,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,Inactive,1.0,N,5.62,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.05585,NaN,48124.55,55.21500,NaN,NaN,NaN,31005.09,48124.55,55.21500,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,Profiled-Urban,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,04: Conservative Urban Middle Class,05: SEC B2,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,Yes,0,Yes,0,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"04: ""Super Premium"" INR 3,500 – 7,000",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,01: Basic,01: National,0,Yes,02: Moderate Priced,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4984,5077,6,Housewife,NaN,Retail,Individual,T30,71.0,Retail,Retail,Retail,2021-11-25,N,2021-11-25,STP,49997.50,0.00,49997.50,1.00,1.0,NaN,1,0.99,0.99,NaN,Online,MUTUAL FUND DISTRIBUTOR,MUTUAL FUND DISTRIBUTOR,Equity,Lumpsum,Kotak Multicap Fund,49998.0,49998.0,NaN,1.0,1,49997.50,NaN,NaN,53857.10,53857.10,NaN,NaN,1.0,1.0,Active,1.0,N,1.16,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53857.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,NaN,NaN,0.98099,49998.0,0.00,7.71959,NaN,NaN,NaN,49997.50,0.00,7.71959,NaN,NaN,NaN,0.077637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4985,5078,8,Others,M,Retail,Individual,T30,82.0,Retail,Retail,Retail,2022-05-02,S,2022-05-02,Distributor,0.00,24973.75,24973.75,0.00,NaN,2.0,2,0.55,0.55,0.55,Online,BANKS,BANKS,Equity,SIP,Kotak Emerging Equity,24974.0,NaN,4987.0,5.0,5,24973.75,NaN,NaN,26554.50,26554.50,NaN,NaN,1.0,1.0,Active,1.0,N,0.55,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24974.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,Very High,1.0,5000.0,0.38089,24974.0,0.00,6.32965,NaN,NaN,NaN,24973.75,0.00,6.32965,NaN,NaN,NaN,0.171723,NaN,NaN,NaN,Profiled-Urban,"06: Very Good INR 1,70,000 – 2,30,000",02: Sub-Metropolitan Urban Area,02: Urban New Wealth,03: SEC A3,0,01: Health Care - ‘The Informed’ In Urban India,01: Saving Plan,Yes,Yes,Yes,Yes,Yes,03: Expected heavy / Frequent Use,0,0,0,0,0,Yes,0,Yes,0,0,Yes,0,04: INR 1 - 4 Crore,02: Premium Fabric Products,Yes,03: Premium Classified Products,02: Premium Classified Products,03: Premium Classified Products,"05: ""Luxury"" INR 7,000+",01: Branded Jewellery,04: High priced Gold Jewellery,06: High priced Diamond Jewellery,02: Luxury,01: International,Yes,Yes,01: High Priced,nan,nan,nan,nan,nan,06: Premium Sports Bike Segment,nan,nan,nan,nan

In [11]:
df1 = df[['VINTAGE_DATE', 'LAST_RECENCY_DATE', 'PAN Key', 'RECENCY', 'GROSS_SALES','NO_OF_PURCHASES']].copy()

#converting string to date time objects

df1['VINTAGE_DATE'] = pd.to_datetime(df1['VINTAGE_DATE'])
df1['LAST_RECENCY_DATE'] = pd.to_datetime(df1['LAST_RECENCY_DATE'])

#finding number of days

df1['num_days'] = (df1['LAST_RECENCY_DATE'] - df1['VINTAGE_DATE']).dt.days

df1

,VINTAGE_DATE,LAST_RECENCY_DATE,PAN Key,RECENCY,GROSS_SALES,NO_OF_PURCHASES,num_days
0,2017-10-24,2021-01-14,1,1.85,11165243.0,1,1178.0
1,2018-01-04,2022-08-22,2,0.25,18195798.0,4,1691.0
2,2017-09-18,2022-09-28,3,0.15,11577903.0,11,1836.0
3,2015-07-17,2022-10-25,4,0.07,67868914.0,13,2657.0
4,2017-06-12,2020-04-13,5,2.61,295000.0,6,1036.0
...,...,...,...,...,...,...,...
4981,2017-03-27,2022-09-07,5074,0.20,63148250.0,16,1990.0
4982,2018-01-09,2021-09-29,5075,1.15,326988.0,1,1359.0
4983,2009-09-11,2020-10-30,5076,2.06,31005.0,1,4067.0
4984,2021-11-25,2021-11-25,5077,0.99,49998.0,1,0.0
4985,2022-05-02,2022-05-02,5078,0.55,24974.0,2,0.0

In [12]:
def safe_divide(x, y):
     if y == 0:
         return 0
     else:
        return x / y

df1['Frequency'] = df1.apply(lambda row: safe_divide(row['NO_OF_PURCHASES'], row['num_days']), axis=1)

df1

,VINTAGE_DATE,LAST_RECENCY_DATE,PAN Key,RECENCY,GROSS_SALES,NO_OF_PURCHASES,num_days,Frequency
0,2017-10-24,2021-01-14,1,1.85,11165243.0,1,1178.0,0.000849
1,2018-01-04,2022-08-22,2,0.25,18195798.0,4,1691.0,0.002365
2,2017-09-18,2022-09-28,3,0.15,11577903.0,11,1836.0,0.005991
3,2015-07-17,2022-10-25,4,0.07,67868914.0,13,2657.0,0.004893
4,2017-06-12,2020-04-13,5,2.61,295000.0,6,1036.0,0.005792
...,...,...,...,...,...,...,...,...
4981,2017-03-27,2022-09-07,5074,0.20,63148250.0,16,1990.0,0.008040
4982,2018-01-09,2021-09-29,5075,1.15,326988.0,1,1359.0,0.000736
4983,2009-09-11,2020-10-30,5076,2.06,31005.0,1,4067.0,0.000246
4984,2021-11-25,2021-11-25,5077,0.99,49998.0,1,0.0,0.000000
4985,2022-05-02,2022-05-02,5078,0.55,24974.0,2,0.0,0.000000

In [13]:
df1.drop(['VINTAGE_DATE', 'LAST_RECENCY_DATE','num_days','NO_OF_PURCHASES'], axis=1, inplace=True)

df1

      PAN Key  RECENCY  GROSS_SALES  Frequency
0           1     1.85   11165243.0   0.000849
1           2     0.25   18195798.0   0.002365
2           3     0.15   11577903.0   0.005991
3           4     0.07   67868914.0   0.004893
4           5     2.61     295000.0   0.005792
...       ...      ...          ...        ...
4981     5074     0.20   63148250.0   0.008040
4982     5075     1.15     326988.0   0.000736
4983     5076     2.06      31005.0   0.000246
4984     5077     0.99      49998.0   0.000000
4985     5078     0.55      24974.0   0.000000

[4986 rows x 4 columns]

In [14]:
df1.rename(columns={'GROSS_SALES': 'Monetary'}, inplace=True)

In [15]:
df1['R_rank'] = df1['RECENCY'].rank(ascending=False)
df1['F_rank'] = df1['Frequency'].rank(ascending=True)
df1['M_rank'] = df1['Monetary'].rank(ascending=True)
df1

      PAN Key  RECENCY    Monetary  Frequency  R_rank  F_rank  M_rank
0           1     1.85  11165243.0   0.000849  2421.5  1436.0  4771.0
1           2     0.25  18195798.0   0.002365  4316.5  2283.0  4815.0
2           3     0.15  11577903.0   0.005991  4486.0  3244.0  4777.0
3           4     0.07  67868914.0   0.004893  4637.0  3077.0  4865.0
4           5     2.61    295000.0   0.005792  2073.0  3216.0  3435.0
...       ...      ...         ...        ...     ...     ...     ...
4981     5074     0.20  63148250.0   0.008040  4383.0  3485.0  4861.0
4982     5075     1.15    326988.0   0.000736  3159.0  1373.0  3562.0
4983     5076     2.06     31005.0   0.000246  2293.0  1117.0  1147.0
4984     5077     0.99     49998.0   0.000000  3398.5   532.0  1533.5
4985     5078     0.55     24974.0   0.000000  3960.0   532.0   948.0

[4986 rows x 7 columns]

In [16]:
# normalizing the rank of the customers
df1['R_rank_norm'] = (df1['R_rank']/df1['R_rank'].max())*100
df1['F_rank_norm'] = (df1['F_rank']/df1['F_rank'].max())*100
df1['M_rank_norm'] = (df1['F_rank']/df1['M_rank'].max())*100
df1.drop(columns=['R_rank', 'F_rank', 'M_rank'], inplace=True)
df1

,PAN Key,RECENCY,Monetary,Frequency,R_rank_norm,F_rank_norm,M_rank_norm
0,1,1.85,11165243.0,0.000849,49.172505,29.492709,29.303132
1,2,0.25,18195798.0,0.002365,87.653569,46.888478,46.587083
2,3,0.15,11577903.0,0.005991,91.095543,66.625590,66.197327
3,4,0.07,67868914.0,0.004893,94.161844,63.195728,62.789511
4,5,2.61,295000.0,0.005792,42.095644,66.050524,65.625957
...,...,...,...,...,...,...,...
4981,5074,0.20,63148250.0,0.008040,89.003960,71.575272,71.115192
4982,5075,1.15,326988.0,0.000736,64.148645,28.198809,28.017549
4983,5076,2.06,31005.0,0.000246,46.563103,22.941056,22.793592
4984,5077,0.99,49998.0,0.000000,69.012082,10.926268,10.856035
4985,5078,0.55,24974.0,0.000000,80.414255,10.926268,10.856035

In [17]:
df1['RFM_Score'] = ((0.15 * df1['R_rank_norm'])+ (0.28 * df1['F_rank_norm']) + (0.57 * df1['M_rank_norm']))
df1['RFM_Score'] *= 0.05
df1 = df1.round(2)
df1

,PAN Key,RECENCY,Monetary,Frequency,R_rank_norm,F_rank_norm,M_rank_norm,RFM_Score
0,1,1.85,11165243.0,0.00,49.17,29.49,29.30,1.62
1,2,0.25,18195798.0,0.00,87.65,46.89,46.59,2.64
2,3,0.15,11577903.0,0.01,91.10,66.63,66.20,3.50
3,4,0.07,67868914.0,0.00,94.16,63.20,62.79,3.38
4,5,2.61,295000.0,0.01,42.10,66.05,65.63,3.11
...,...,...,...,...,...,...,...,...
4981,5074,0.20,63148250.0,0.01,89.00,71.58,71.12,3.70
4982,5075,1.15,326988.0,0.00,64.15,28.20,28.02,1.67
4983,5076,2.06,31005.0,0.00,46.56,22.94,22.79,1.32
4984,5077,0.99,49998.0,0.00,69.01,10.93,10.86,0.98
4985,5078,0.55,24974.0,0.00,80.41,10.93,10.86,1.07

In [18]:
df2 = df1[['PAN Key', 'RFM_Score']].copy()
df2

      PAN Key  RFM_Score
0           1       1.62
1           2       2.64
2           3       3.50
3           4       3.38
4           5       3.11
...       ...        ...
4981     5074       3.70
4982     5075       1.67
4983     5076       1.32
4984     5077       0.98
4985     5078       1.07

[4986 rows x 2 columns]

Rating Customer based upon the RFM score
rfm score >4.5 : Top Customer
4.5 > rfm score > 4 : High Value Customer
4>rfm score >3 : Medium value customer
3>rfm score>1.6 : Low-value customer
rfm score<1.6 :Lost Customer

In [19]:
df2["Customer_segment"] = np.where(df2['RFM_Score'] >4.5, "Top Customers",(np.where(df2['RFM_Score'] > 4,"High value Customer",(np.where(df2['RFM_Score'] > 3,"Medium Value Customer",np.where(df2['RFM_Score'] > 1.6,'Low Value Customers', 'Lost Customers'))))))

df2

      PAN Key  RFM_Score       Customer_segment
0           1       1.62    Low Value Customers
1           2       2.64    Low Value Customers
2           3       3.50  Medium Value Customer
3           4       3.38  Medium Value Customer
4           5       3.11  Medium Value Customer
...       ...        ...                    ...
4981     5074       3.70  Medium Value Customer
4982     5075       1.67    Low Value Customers
4983     5076       1.32         Lost Customers
4984     5077       0.98         Lost Customers
4985     5078       1.07         Lost Customers

[4986 rows x 3 columns]

In [20]:
df3 = df2.loc[df2['Customer_segment'] == 'Top Customers']
df3

      PAN Key  RFM_Score Customer_segment
28         29       4.66    Top Customers
32         33       4.74    Top Customers
52         53       4.53    Top Customers
56         57       4.78    Top Customers
131       132       4.73    Top Customers
...       ...        ...              ...
4884     4977       4.55    Top Customers
4911     5004       4.80    Top Customers
4919     5012       4.57    Top Customers
4938     5031       4.63    Top Customers
4949     5042       4.68    Top Customers

[187 rows x 3 columns]

In [21]:
df3.describe(include = 'all')

            PAN Key   RFM_Score Customer_segment
count    187.000000  187.000000              187
unique          NaN         NaN                1
top             NaN         NaN    Top Customers
freq            NaN         NaN              187
mean    2579.994652    4.675615              NaN
std     1414.599159    0.111186              NaN
min       29.000000    4.510000              NaN
25%     1472.500000    4.580000              NaN
50%     2580.000000    4.660000              NaN
75%     3692.000000    4.760000              NaN
max     5042.000000    4.960000              NaN

In [22]:
df1

,PAN Key,RECENCY,Monetary,Frequency,R_rank_norm,F_rank_norm,M_rank_norm,RFM_Score
0,1,1.85,11165243.0,0.00,49.17,29.49,29.30,1.62
1,2,0.25,18195798.0,0.00,87.65,46.89,46.59,2.64
2,3,0.15,11577903.0,0.01,91.10,66.63,66.20,3.50
3,4,0.07,67868914.0,0.00,94.16,63.20,62.79,3.38
4,5,2.61,295000.0,0.01,42.10,66.05,65.63,3.11
...,...,...,...,...,...,...,...,...
4981,5074,0.20,63148250.0,0.01,89.00,71.58,71.12,3.70
4982,5075,1.15,326988.0,0.00,64.15,28.20,28.02,1.67
4983,5076,2.06,31005.0,0.00,46.56,22.94,22.79,1.32
4984,5077,0.99,49998.0,0.00,69.01,10.93,10.86,0.98
4985,5078,0.55,24974.0,0.00,80.41,10.93,10.86,1.07

In [23]:
df4 = df[['AGE','LATENCY_CLEAN','ONLINE_OFFLINE_TAG','GENDER','GROSS_SALES','STATUS','REGISTERED_ONLINE','RISK_APPETITE','Income','Urban','Saving Plan', 'Retirement Plan']].copy()
df4

,AGE,LATENCY_CLEAN,ONLINE_OFFLINE_TAG,GENDER,GROSS_SALES,STATUS,REGISTERED_ONLINE,RISK_APPETITE,Income,Urban,Saving Plan,Retirement Plan
0,NaN,NaN,Offline,NaN,11165243.0,Active,N,Moderate,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
1,NaN,1.63,Offline,NaN,18195798.0,Active,N,Very High,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
2,NaN,0.52,Online,NaN,11577903.0,Active,N,Low to Moderate,"03: Medium INR 40,000 – 80,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
3,66.0,0.61,Offline,M,67868914.0,Active,N,High,"08: Very High INR > 3,00,000",01: Cosmopolitan Urban Area,01: Saving Plan,0
4,63.0,1.09,Online,M,295000.0,Active,Y,High,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,Offline,NaN,63148250.0,Active,N,Low to Moderate,"07: High INR 2,30,000 – 3,00,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
4982,58.0,2.72,Offline,M,326988.0,Active,Y,Very High,NaN,NaN,nan,nan
4983,56.0,5.62,Offline,M,31005.0,Inactive,Y,NaN,"05: Good INR 1,30,000 – 1,70,000",01: Cosmopolitan Urban Area,01: Saving Plan,Yes
4984,71.0,1.16,Online,NaN,49998.0,Active,N,Very High,NaN,NaN,nan,nan
4985,82.0,0.55,Online,M,24974.0,Active,N,Very High,"06: Very Good INR 1,70,000 – 2,30,000",02: Sub-Metropolitan Urban Area,01: Saving Plan,Yes

In [24]:
df4.columns.values

array(['AGE', 'LATENCY_CLEAN', 'ONLINE_OFFLINE_TAG', 'GENDER',
       'GROSS_SALES', 'STATUS', 'REGISTERED_ONLINE', 'RISK_APPETITE',
       'Income', 'Urban', 'Saving Plan', 'Retirement Plan'], dtype=object)

In [25]:
df_encoded = pd.get_dummies(df4, columns=['ONLINE_OFFLINE_TAG','GENDER','STATUS','REGISTERED_ONLINE','RISK_APPETITE','Income'])

In [26]:
df_encoded

,AGE,LATENCY_CLEAN,GROSS_SALES,Urban,Saving Plan,Retirement Plan,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000"
0,NaN,NaN,11165243.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0
1,NaN,1.63,18195798.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0
2,NaN,0.52,11577903.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0
3,66.0,0.61,67868914.0,01: Cosmopolitan Urban Area,01: Saving Plan,0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1
4,63.0,1.09,295000.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0
4982,58.0,2.72,326988.0,NaN,nan,nan,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
4983,56.0,5.62,31005.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
4984,71.0,1.16,49998.0,NaN,nan,nan,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
4985,82.0,0.55,24974.0,02: Sub-Metropolitan Urban Area,01: Saving Plan,Yes,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0

In [27]:
df_encoded.corr()

,AGE,LATENCY_CLEAN,GROSS_SALES,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000"
AGE,1.000000,0.206041,-0.069581,0.161003,-0.241723,0.077433,0.034128,-0.048212,0.048212,0.073339,-0.073339,0.056043,0.048055,0.038106,0.059246,0.049707,-0.133835,-0.043748,-0.064396,-0.010533,0.042504,0.087663,0.129542
LATENCY_CLEAN,0.206041,1.000000,-0.023333,0.252268,-0.323591,0.107579,0.047204,-0.048007,0.048007,0.028041,-0.028041,-0.026784,-0.016785,-0.046218,-0.051041,-0.039200,0.006668,0.000438,-0.001674,-0.000113,0.020008,0.034283,0.046123
GROSS_SALES,-0.069581,-0.023333,1.000000,0.024945,-0.023319,-0.014184,-0.021085,-0.001637,0.001637,0.009720,-0.009720,-0.004466,-0.002508,-0.003425,-0.002779,-0.003997,-0.033273,-0.007976,0.039206,-0.012816,-0.009399,-0.006532,-0.004803
ONLINE_OFFLINE_TAG_Offline,0.161003,0.252268,0.024945,1.000000,-0.888262,0.154240,0.078132,0.031849,-0.031849,-0.096398,0.096398,0.023093,0.002740,-0.033282,-0.046202,-0.016199,0.032107,-0.008496,-0.012142,-0.004083,-0.010794,0.039823,0.054800
ONLINE_OFFLINE_TAG_Online,-0.241723,-0.323591,-0.023319,-0.888262,1.000000,-0.141264,-0.064190,0.028739,-0.028739,0.078684,-0.078684,-0.029203,-0.006671,0.037025,0.047336,0.003025,0.017386,0.012061,0.028595,0.018847,0.014566,-0.061430,-0.099299
GENDER_F,0.077433,0.107579,-0.014184,0.154240,-0.141264,1.000000,-0.491281,-0.008353,0.008353,-0.027102,0.027102,0.026401,0.023714,-0.002973,-0.032182,0.005856,-0.022589,-0.046509,-0.015157,0.025489,0.035097,0.034171,0.064970
GENDER_M,0.034128,0.047204,-0.021085,0.078132,-0.064190,-0.491281,1.000000,-0.040472,0.040472,-0.131123,0.131123,-0.025052,-0.033571,0.012063,0.023436,0.013404,-0.028985,0.029785,0.031617,-0.021371,-0.017099,0.007015,-0.012754
STATUS_Active,-0.048212,-0.048007,-0.001637,0.031849,0.028739,-0.008353,-0.040472,1.000000,-1.000000,0.021521,-0.021521,0.092400,0.049545,0.061632,0.088741,0.076873,0.637429,-0.009723,-0.003885,-0.015056,0.006673,-0.020993,-0.042766
STATUS_Inactive,0.048212,0.048007,0.001637,-0.031849,-0.028739,0.008353,0.040472,-1.000000,1.000000,-0.021521,0.021521,-0.092400,-0.049545,-0.061632,-0.088741,-0.076873,-0.637429,0.009723,0.003885,0.015056,-0.006673,0.020993,0.042766
REGISTERED_ONLINE_N,0.073339,0.028041,0.009720,-0.096398,0.078684,-0.027102,-0.131123,0.021521,-0.021521,1.000000,-1.000000,0.006145,0.010298,-0.048339,-0.002756,-0.020940,0.023510,-0.020973,-0.013387,0.012484,-0.000006,-0.000126,0.012940
REGISTERED_ONLINE_Y,-0.073339,-0.028041,-0.009720,0.096398,-0.078684,0.027102,0.131123,-0.021521,0.021521,-1.000000,1.000000,-0.006145,-0.010298,0.048339,0.002756,0.020940,-0.023510,0.020973,0.013387,-0.012484,0.000006,0.000126,-0.012940
RISK_APPETITE_High,0.056043,-0.026784,-0.004466,0.023093,-0.029203,0.026401,-0.025052,0.092400,-0.092400,0.006145,-0.006145,1.000000,-0.019273,-0.028076,-0.034521,-0.031143,-0.253333,-0.030755,-0.010860,0.007190,0.027251,0.010904,0.008482
RISK_APPETITE_Low,0.048055,-0.016785,-0.002508,0.002740,-0.006671,0.023714,-0.033571,0.049545,-0.049545,0.010298,-0.010298,-0.019273,1.000000,-0.015055,-0.018510,-0.016699,-0.135837,0.001599,0.010458,-0.013260,-0.008497,0.004830,-0.002222
RISK_APPETITE_Low to Moderate,0.038106,-0.046218,-0.003425,-0.033282,0.037025,-0.002973,0.012063,0.061632,-0.061632,-0.048339,0.048339,-0.028076,-0.015055,1.000000,-0.026965,-0.024326,-0.197881,-0.014266,0.000962,-0.011787,-0.022772,-0.000693,0.057224
RISK_APPETITE_Moderate,0.059246,-0.051041,-0.002779,-0.046202,0.047336,-0.032182,0.023436,0.088741,-0.088741,-0.002756,0.002756,-0.034521,-0.018510,-0.026965,1.000000,-0.029909,-0.243301,0.008000,-0.007460,-0.026817,0.003019,-0.002985,0.021970
RISK_APPETITE_Moderately High,0.049707,-0.039200,-0.003997,-0.016199,0.003025,0.005856,0.013404,0.076873,-0.076873,-0.020940,0.020940,-0.031143,-0.016699,-0.024326,-0.029909,1.000000,-0.219492,-0.022588,-0.003192,0.004592,-0.024481,-0.003636,0.023497
RISK_APPETITE_Very High,-0.133835,0.006668,-0.033273,0.032107,0.017386,-0.022589,-0.028985,0.637429,-0.637429,0.023510,-0.023510,-0.253333,-0.135837,-0.197881,-0.243301,-0.219492,1.000000,0.021971,0.008485,-0.003204,-0.004922,-0.014775,-0.066735
"Income_03: Medium INR 40,000 – 80,000",-0.043748,0.000438,-0.007976,-0.008496,0.012061,-0.046509,0.029785,-0.009723,0.009723,-0.020973,0.020973,-0.030755,0.001599,-0.014266,0.008000,-0.022588,0.021971,1.000000,-0.194358,-0.165540,-0.121777,-0.085759,-0.084087
"Income_04: Medium Good INR 80,000 – 1,30,000",-0.064396,-0.001674,0.039206,-0.012142,0.028595,-0.015157,0.031617,-0.003885,0.003885,-0.013387,0.013387,-0.010860,0.010458,0.000962,-0.007460,-0.003192,0.008485,-0.194358,1.000000,-0.312075,-0.229572,-0.161672,-0.158519
"Income_05: Good INR 1,30,000 – 1,70,000",-0.010533,-0.000113,-0.012816,-0.004083,0.018847,0.025489,-0.021371,-0.015056,0.015056,0.012484,-0.012484,0.007190,-0.013260,-0.011787,-0.026817,0.004592,-0.003204,-0.165540,-0.312075,1.000000,-0.195533,-0.137701,-0.135015
"Income_06: Very Good INR 1,70,000 – 2,30,000",0.042504,0.020008,-0.009399,-0.010794,0.014566,0.035097,-0.017099,0.006673,-0.006673,-0.000006,0.000006,0.027251,-0.008497,-0.022772,0.003019,-0.024481,-0.004922,-0.121777,-0.229572,-0.195533,1.000000,-0.101297,-0.099321
"Income_07: High INR 2,30,000 – 3,00,000",0.087663,0.034283,-0.006532,0.039823,-0.061430,0.034171,0.007015,-0.020993,0.020993,-0.000126,0.000126,0.010904,0.004830,-0.000693,-0.002985,-0.003636,-0.014775,-0.085759,-0.161672,-0.137701,-0.101297,1.000000,-0.069945
"Income_08: Very High INR > 3,00,000",0.129542,0.046123,-0.004803,0.054800,-0.099299,0.064970,-0.012754,-0.042766,0.042766,0.012940,-0.012940,0.008482,-0.002222,0.057224,0.021970,0.023497,-0.066735,-0.084087,-0.158519,-0.135015,-0.099321,-0.069945,1.000000

In [28]:
df_concatenated = pd.concat([df_encoded, df1], axis=1)
df_concatenated

,AGE,LATENCY_CLEAN,GROSS_SALES,Urban,Saving Plan,Retirement Plan,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000",PAN Key,RECENCY,Monetary,Frequency,R_rank_norm,F_rank_norm,M_rank_norm,RFM_Score
0,NaN,NaN,11165243.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1.85,11165243.0,0.00,49.17,29.49,29.30,1.62
1,NaN,1.63,18195798.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,2,0.25,18195798.0,0.00,87.65,46.89,46.59,2.64
2,NaN,0.52,11577903.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0.15,11577903.0,0.01,91.10,66.63,66.20,3.50
3,66.0,0.61,67868914.0,01: Cosmopolitan Urban Area,01: Saving Plan,0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,4,0.07,67868914.0,0.00,94.16,63.20,62.79,3.38
4,63.0,1.09,295000.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,5,2.61,295000.0,0.01,42.10,66.05,65.63,3.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5074,0.20,63148250.0,0.01,89.00,71.58,71.12,3.70
4982,58.0,2.72,326988.0,NaN,nan,nan,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,5075,1.15,326988.0,0.00,64.15,28.20,28.02,1.67
4983,56.0,5.62,31005.0,01: Cosmopolitan Urban Area,01: Saving Plan,Yes,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,5076,2.06,31005.0,0.00,46.56,22.94,22.79,1.32
4984,71.0,1.16,49998.0,NaN,nan,nan,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,5077,0.99,49998.0,0.00,69.01,10.93,10.86,0.98
4985,82.0,0.55,24974.0,02: Sub-Metropolitan Urban Area,01: Saving Plan,Yes,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,5078,0.55,24974.0,0.00,80.41,10.93,10.86,1.07

In [29]:
df_concatenated.drop(columns=['Urban', 'Saving Plan', 'Retirement Plan','R_rank_norm','F_rank_norm','M_rank_norm'], inplace=True)

df_concatenated

,AGE,LATENCY_CLEAN,GROSS_SALES,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000",PAN Key,RECENCY,Monetary,Frequency,RFM_Score
0,NaN,NaN,11165243.0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1.85,11165243.0,0.00,1.62
1,NaN,1.63,18195798.0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,2,0.25,18195798.0,0.00,2.64
2,NaN,0.52,11577903.0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0.15,11577903.0,0.01,3.50
3,66.0,0.61,67868914.0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,4,0.07,67868914.0,0.00,3.38
4,63.0,1.09,295000.0,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,5,2.61,295000.0,0.01,3.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5074,0.20,63148250.0,0.01,3.70
4982,58.0,2.72,326988.0,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,5075,1.15,326988.0,0.00,1.67
4983,56.0,5.62,31005.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,5076,2.06,31005.0,0.00,1.32
4984,71.0,1.16,49998.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,5077,0.99,49998.0,0.00,0.98
4985,82.0,0.55,24974.0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,5078,0.55,24974.0,0.00,1.07

In [30]:
df_concatenated = df_concatenated.assign(churn=df_concatenated['STATUS_Inactive'])

In [31]:
df_concatenated

,AGE,LATENCY_CLEAN,GROSS_SALES,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000",PAN Key,RECENCY,Monetary,Frequency,RFM_Score,churn
0,NaN,NaN,11165243.0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1.85,11165243.0,0.00,1.62,0
1,NaN,1.63,18195798.0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,2,0.25,18195798.0,0.00,2.64,0
2,NaN,0.52,11577903.0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0.15,11577903.0,0.01,3.50,0
3,66.0,0.61,67868914.0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,4,0.07,67868914.0,0.00,3.38,0
4,63.0,1.09,295000.0,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,5,2.61,295000.0,0.01,3.11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5074,0.20,63148250.0,0.01,3.70,0
4982,58.0,2.72,326988.0,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,5075,1.15,326988.0,0.00,1.67,0
4983,56.0,5.62,31005.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,5076,2.06,31005.0,0.00,1.32,1
4984,71.0,1.16,49998.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,5077,0.99,49998.0,0.00,0.98,0
4985,82.0,0.55,24974.0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,5078,0.55,24974.0,0.00,1.07,0

In [32]:
df_concatenated = df_concatenated.dropna()
df_concatenated

,AGE,LATENCY_CLEAN,GROSS_SALES,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000",PAN Key,RECENCY,Monetary,Frequency,RFM_Score,churn
3,66.0,0.61,67868914.0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,4,0.07,67868914.0,0.00,3.38,0
4,63.0,1.09,295000.0,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,5,2.61,295000.0,0.01,3.11,0
5,53.0,0.96,183632.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,6,1.45,183632.0,0.00,3.00,0
6,63.0,2.06,108976.0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,7,1.15,108976.0,0.00,2.09,0
7,57.0,2.72,240000.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,8,6.33,240000.0,0.03,3.74,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5074,0.20,63148250.0,0.01,3.70,0
4982,58.0,2.72,326988.0,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,5075,1.15,326988.0,0.00,1.67,0
4983,56.0,5.62,31005.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,5076,2.06,31005.0,0.00,1.32,1
4984,71.0,1.16,49998.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,5077,0.99,49998.0,0.00,0.98,0
4985,82.0,0.55,24974.0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,5078,0.55,24974.0,0.00,1.07,0

In [33]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [34]:
X = df_concatenated.drop(['churn'], axis=1)
y = df_concatenated['churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [36]:
y_pred = rfc.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Precision:', precision_score(y_test, y_pred))
print('Recall:', recall_score(y_test, y_pred))
print('F1-score:', f1_score(y_test, y_pred))

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0

In [38]:
propensity = rfc.predict_proba(X)[:, 1]

In [40]:
df_concatenated['churn_propensity'] = propensity

C:\Users\user\AppData\Local\Temp\ipykernel_2932\3094464873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_concatenated['churn_propensity'] = propensity

In [42]:
threshold = 0.5
df_concatenated['churn_prediction'] = df_concatenated['churn_propensity'].apply(lambda x: 1 if x >= threshold else 0)

C:\Users\user\AppData\Local\Temp\ipykernel_2932\1996252018.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_concatenated['churn_prediction'] = df_concatenated['churn_propensity'].apply(lambda x: 1 if x >= threshold else 0)

In [44]:
df_concatenated

,AGE,LATENCY_CLEAN,GROSS_SALES,ONLINE_OFFLINE_TAG_Offline,ONLINE_OFFLINE_TAG_Online,GENDER_F,GENDER_M,STATUS_Active,STATUS_Inactive,REGISTERED_ONLINE_N,REGISTERED_ONLINE_Y,RISK_APPETITE_High,RISK_APPETITE_Low,RISK_APPETITE_Low to Moderate,RISK_APPETITE_Moderate,RISK_APPETITE_Moderately High,RISK_APPETITE_Very High,"Income_03: Medium INR 40,000 – 80,000","Income_04: Medium Good INR 80,000 – 1,30,000","Income_05: Good INR 1,30,000 – 1,70,000","Income_06: Very Good INR 1,70,000 – 2,30,000","Income_07: High INR 2,30,000 – 3,00,000","Income_08: Very High INR > 3,00,000",PAN Key,RECENCY,Monetary,Frequency,RFM_Score,churn,churn_propensity,churn_prediction
3,66.0,0.61,67868914.0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,4,0.07,67868914.0,0.00,3.38,0,0.002222,0
4,63.0,1.09,295000.0,0,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,5,2.61,295000.0,0.01,3.11,0,0.000000,0
5,53.0,0.96,183632.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,6,1.45,183632.0,0.00,3.00,0,0.000000,0
6,63.0,2.06,108976.0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,7,1.15,108976.0,0.00,2.09,0,0.001250,0
7,57.0,2.72,240000.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,8,6.33,240000.0,0.03,3.74,1,0.995977,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,64.0,0.38,63148250.0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5074,0.20,63148250.0,0.01,3.70,0,0.000000,0
4982,58.0,2.72,326988.0,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,5075,1.15,326988.0,0.00,1.67,0,0.000000,0
4983,56.0,5.62,31005.0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,5076,2.06,31005.0,0.00,1.32,1,0.993719,1
4984,71.0,1.16,49998.0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,5077,0.99,49998.0,0.00,0.98,0,0.001176,0
4985,82.0,0.55,24974.0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,5078,0.55,24974.0,0.00,1.07,0,0.000000,0